//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Songs = new HashSet<Song>();
            this.Playlists = new HashSet<Playlist>();
        }
    
        public int LoginId { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<Song> Songs { get; set; }
        public virtual ICollection<Playlist> Playlists { get; set; }
    }
}
