//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Genres = new HashSet<Genre>();
        }
    
        public int Id { get; set; }
        public string sTitle { get; set; }
    
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual Artist Artist { get; set; }
    }
}
